version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fuse
      POSTGRES_PASSWORD: fusepass
      POSTGRES_DB: fusedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # web UI
      - "1025:1025"  # SMTP server

volumes:
  pgdata: